---
title: "US DropZones"
author: "Alex MacCalman"
date: "8/10/2020"
output: html_document
---

# Map of Skydiving Dropzones in the United States  
```{r, echo=FALSE, include=FALSE}
library(sf)
library(dplyr)
library(leaflet)
library(knitr)
```

This page shows a map of all skydiving dropzones in the United States. Data for this map was downloaded from google at teh following website ass a kml file: https://www.google.com/maps/d/viewer?ie=UTF8&t=m&oe=UTF8&msa=0&mid=1ItKSNh2yynMbiJIf-hp8tyIUEPo&ll=44.911080614651326%2C-113.43712099999999&z=4

First we will load in the data and get it ready.
```{r loadData, echo=FALSE}
dzData <- tibble(st_read("Skydiving_Drop_Zones-United_States.kml"))
coord <- st_coordinates(dzData$geometry)
dzData <- mutate(dzData, lng = coord[,1]) %>% 
  mutate(lat = coord[,2])
dz <- select(dzData, lat, lng, Name)

```

Now we will create a map cluster of dropzones.  
```{r cluster, echo=FALSE}
dz %>% 
  leaflet() %>% 
  addTiles() %>% 
#  addMarkers(lat = dz$lat, lng = dz$lng, popup = dzData$Name)
  addMarkers(clusterOptions = markerClusterOptions(), popup = dz$Name)
```

